import type {
  ChurchEvent,
  CommunicationChannel,
  EventCalendarView,
  EventCategory,
  EventColorKey,
  EventDepartment,
  EventFormDraft,
  EventRecurrenceFrequency,
} from "@/churchTypes/events";

export const EVENT_CALENDAR_VIEWS: EventCalendarView[] = [
  "month",
  "week",
  "day",
  "agenda",
];

export const EVENT_CATEGORIES: EventCategory[] = [
  "Sabbath Service",
  "Divine Service",
  "AY Program",
  "Evangelism",
  "Pathfinder",
  "Communion",
  "Prayer Meeting",
  "Camp Meeting",
  "Health Seminar",
  "Bible Study",
  "Choir Practice",
  "Board Meeting",
  "Baptism Class",
  "Community Outreach",
];

export const EVENT_DEPARTMENTS: EventDepartment[] = [
  "Pastoral",
  "Sabbath School",
  "Youth",
  "Pathfinder",
  "Evangelism",
  "Health",
  "Music",
  "Treasury",
  "Clerk",
  "Community Services",
  "Board",
];

export const RECURRENCE_OPTIONS: EventRecurrenceFrequency[] = [
  "None",
  "Weekly",
  "Monthly",
  "Quarterly",
  "Annual",
];

export const COMMUNICATION_CHANNELS: CommunicationChannel[] = [
  "Email",
  "SMS",
  "WhatsApp",
  "Push",
];

export const EVENT_CATEGORY_COLOR_KEY: Record<EventCategory, EventColorKey> = {
  "Sabbath Service": "sabbath",
  "Divine Service": "sabbath",
  "AY Program": "youth",
  Evangelism: "evangelism",
  Pathfinder: "pathfinder",
  Communion: "communion",
  "Prayer Meeting": "prayer",
  "Camp Meeting": "evangelism",
  "Health Seminar": "health",
  "Bible Study": "prayer",
  "Choir Practice": "choir",
  "Board Meeting": "board",
  "Baptism Class": "evangelism",
  "Community Outreach": "health",
};

export const DEFAULT_EVENT_DRAFT: EventFormDraft = {
  title: "",
  description: "",
  department: "Pastoral",
  category: "Sabbath Service",
  venue: "Main sanctuary",
  start: "2026-05-23T08:30",
  end: "2026-05-23T13:00",
  recurrenceFrequency: "Weekly",
  speaker: "",
  capacity: 420,
  registrationRequired: false,
  volunteersNeeded: 12,
  budgetAllocated: 0,
  attachments: "",
  communicationChannels: ["Email", "SMS", "WhatsApp"],
};

export const SDA_EVENTS: ChurchEvent[] = [
  {
    id: "EVT-001",
    title: "Sabbath Worship and Divine Service",
    description:
      "Weekly Sabbath School, worship service, divine service, and pastoral care announcements.",
    department: "Pastoral",
    category: "Sabbath Service",
    colorKey: "sabbath",
    venue: "Main sanctuary",
    start: "2026-05-23T08:30:00",
    end: "2026-05-23T13:00:00",
    recurrence: {
      frequency: "Weekly",
      rule: "Every Sabbath morning",
    },
    speaker: "Pr. Daniel Kato",
    capacity: 520,
    registrationRequired: false,
    volunteersNeeded: 22,
    budgetAllocated: 1100000,
    budgetSpent: 860000,
    status: "Approved",
    attendance: {
      registered: 0,
      actual: 438,
      members: 397,
      visitors: 41,
      followUpRequired: 14,
      conversions: 3,
      baptisms: 0,
    },
    volunteers: [
      {
        role: "Elder on duty",
        assignee: "Elder Moses K.",
        department: "Pastoral",
        status: "Confirmed",
        callTime: "08:00",
      },
      {
        role: "Chorister",
        assignee: "Sarah N.",
        department: "Music",
        status: "Confirmed",
        callTime: "08:15",
      },
      {
        role: "Pianist",
        assignee: "Joel M.",
        department: "Music",
        status: "Assigned",
        callTime: "08:15",
      },
      {
        role: "Deacons",
        assignee: "Deacon team A",
        department: "Pastoral",
        status: "Confirmed",
        callTime: "08:00",
      },
      {
        role: "Media team",
        assignee: "Media rotation 2",
        department: "Music",
        status: "Assigned",
        callTime: "07:45",
      },
      {
        role: "Sabbath School coordinator",
        assignee: "Grace A.",
        department: "Sabbath School",
        status: "Confirmed",
        callTime: "08:00",
      },
    ],
    communications: {
      channels: ["Email", "SMS", "WhatsApp", "Push"],
      rsvpTracking: false,
      automations: [
        "Notify volunteers Friday 18:00",
        "Reminder 24h before event",
        "Follow-up visitors after service",
      ],
    },
    permissions: [
      {
        role: "Pastor",
        scope: "Major worship programs",
        level: "Approve",
      },
      {
        role: "Church clerk",
        scope: "Attendance and reports",
        level: "View all",
      },
    ],
    attachments: [
      {
        type: "Sermon notes",
        name: "Faithfulness in ordinary discipleship.pdf",
        owner: "Pastoral office",
        status: "Ready",
      },
      {
        type: "Recording",
        name: "Livestream archive placeholder",
        owner: "Media team",
        status: "Draft",
      },
    ],
    notes: [
      "Visitor follow-up cards should be handed to the clerk immediately after service.",
      "Media team needs lower-third titles before 09:00.",
    ],
    reports: [
      "Attendance trend: Sabbath attendance is up 7% compared with the previous month.",
      "Volunteer coverage: 19 of 22 roles confirmed.",
    ],
    enterpriseReadiness: [
      { label: "QR check-in", status: "Designed" },
      { label: "Livestream integration", status: "Planned" },
      { label: "Multi-branch synchronization", status: "Planned" },
    ],
  },
  {
    id: "EVT-002",
    title: "AY Program: Digital Discipleship",
    description:
      "Adventist Youth worship, small groups, and mission planning for online outreach.",
    department: "Youth",
    category: "AY Program",
    colorKey: "youth",
    venue: "Youth chapel",
    start: "2026-05-23T16:00:00",
    end: "2026-05-23T18:00:00",
    recurrence: {
      frequency: "Weekly",
      rule: "Every Sabbath afternoon",
    },
    speaker: "Youth Leader Miriam S.",
    capacity: 180,
    registrationRequired: true,
    volunteersNeeded: 10,
    budgetAllocated: 360000,
    budgetSpent: 210000,
    status: "Needs volunteers",
    attendance: {
      registered: 126,
      actual: 96,
      members: 80,
      visitors: 16,
      followUpRequired: 8,
      conversions: 1,
      baptisms: 0,
    },
    volunteers: [
      {
        role: "Program host",
        assignee: "Brian T.",
        department: "Youth",
        status: "Confirmed",
        callTime: "15:30",
      },
      {
        role: "Small-group facilitators",
        assignee: "Youth mentors",
        department: "Youth",
        status: "Assigned",
        callTime: "15:30",
      },
      {
        role: "Media support",
        assignee: "Needed",
        department: "Music",
        status: "Needed",
        callTime: "15:00",
      },
    ],
    communications: {
      channels: ["WhatsApp", "Push"],
      rsvpTracking: true,
      automations: [
        "Reminder 24h before event",
        "Notify volunteers",
        "Follow-up after AY small groups",
      ],
    },
    permissions: [
      {
        role: "Youth leader",
        scope: "AY programs",
        level: "Manage",
      },
      {
        role: "Pastor",
        scope: "Public teaching programs",
        level: "Approve",
      },
    ],
    attachments: [
      {
        type: "Poster",
        name: "AY Digital Discipleship poster.png",
        owner: "Youth media",
        status: "Ready",
      },
    ],
    notes: ["Smart insight: AY attendance dropped 18% over 3 weeks."],
    reports: ["Youth engagement score: 71/100 with media volunteer shortage."],
    enterpriseReadiness: [
      { label: "AI attendance predictions", status: "Designed" },
      { label: "Ministry engagement scoring", status: "Ready" },
    ],
  },
  {
    id: "EVT-003",
    title: "Wednesday Prayer Meeting",
    description:
      "Midweek prayer, testimony sharing, and pastoral care follow-up.",
    department: "Pastoral",
    category: "Prayer Meeting",
    colorKey: "prayer",
    venue: "Main sanctuary",
    start: "2026-05-27T18:00:00",
    end: "2026-05-27T19:30:00",
    recurrence: {
      frequency: "Weekly",
      rule: "Every Wednesday evening",
    },
    speaker: "Elder Rebecca N.",
    capacity: 260,
    registrationRequired: false,
    volunteersNeeded: 6,
    budgetAllocated: 120000,
    budgetSpent: 45000,
    status: "Approved",
    attendance: {
      registered: 0,
      actual: 142,
      members: 128,
      visitors: 14,
      followUpRequired: 6,
      conversions: 0,
      baptisms: 0,
    },
    volunteers: [
      {
        role: "Opening devotion",
        assignee: "Elder Rebecca N.",
        department: "Pastoral",
        status: "Confirmed",
        callTime: "17:45",
      },
      {
        role: "Prayer coordinators",
        assignee: "Prayer band",
        department: "Pastoral",
        status: "Confirmed",
        callTime: "17:45",
      },
    ],
    communications: {
      channels: ["SMS", "WhatsApp"],
      rsvpTracking: false,
      automations: ["Prayer request digest Wednesday 12:00"],
    },
    permissions: [
      {
        role: "Pastor",
        scope: "Prayer meetings",
        level: "Approve",
      },
    ],
    attachments: [
      {
        type: "Report",
        name: "Prayer requests follow-up list",
        owner: "Prayer coordinator",
        status: "Draft",
      },
    ],
    notes: ["Prioritize home visitation requests from visitors."],
    reports: ["Follow-up queue: 6 requests pending."],
    enterpriseReadiness: [
      { label: "Push notifications", status: "Ready" },
      { label: "AI pastoral care suggestions", status: "Planned" },
    ],
  },
  {
    id: "EVT-004",
    title: "Pathfinder Skills and Camp Readiness",
    description:
      "Pathfinder marching, honors preparation, camp planning, and parent briefing.",
    department: "Pathfinder",
    category: "Pathfinder",
    colorKey: "pathfinder",
    venue: "Church grounds",
    start: "2026-05-31T09:00:00",
    end: "2026-05-31T13:00:00",
    recurrence: {
      frequency: "Weekly",
      rule: "Every Sunday until camp meeting",
      until: "2026-07-12",
    },
    speaker: "Director Andrew L.",
    capacity: 140,
    registrationRequired: true,
    volunteersNeeded: 14,
    budgetAllocated: 760000,
    budgetSpent: 420000,
    status: "Pending approval",
    attendance: {
      registered: 84,
      actual: 71,
      members: 69,
      visitors: 2,
      followUpRequired: 4,
      conversions: 0,
      baptisms: 0,
    },
    volunteers: [
      {
        role: "Pathfinder director",
        assignee: "Andrew L.",
        department: "Pathfinder",
        status: "Confirmed",
        callTime: "08:00",
      },
      {
        role: "First aid",
        assignee: "Needed",
        department: "Health",
        status: "Needed",
        callTime: "08:30",
      },
      {
        role: "Transport lead",
        assignee: "Deacon Paul",
        department: "Pathfinder",
        status: "Assigned",
        callTime: "08:30",
      },
    ],
    communications: {
      channels: ["Email", "WhatsApp"],
      rsvpTracking: true,
      automations: [
        "Parent reminder 24h before event",
        "Notify Pathfinder instructors",
      ],
    },
    permissions: [
      {
        role: "Pathfinder director",
        scope: "Camps and Pathfinder operations",
        level: "Manage",
      },
      {
        role: "Pastor",
        scope: "Off-site and budget events",
        level: "Approve",
      },
    ],
    attachments: [
      {
        type: "Budget",
        name: "Camp readiness budget.xlsx",
        owner: "Pathfinder treasury liaison",
        status: "Ready",
      },
      {
        type: "Poster",
        name: "Pathfinder camp readiness flyer.png",
        owner: "Pathfinder secretary",
        status: "Ready",
      },
    ],
    notes: ["First-aid volunteer still required before approval."],
    reports: ["Registration is at 60% of expected camp readiness attendance."],
    enterpriseReadiness: [
      { label: "Ticketing/registration", status: "Designed" },
      { label: "QR check-in", status: "Designed" },
    ],
  },
  {
    id: "EVT-005",
    title: "Church Board Meeting",
    description:
      "Monthly board governance, budget approvals, event approvals, and ministry reports.",
    department: "Board",
    category: "Board Meeting",
    colorKey: "board",
    venue: "Board room",
    start: "2026-05-28T19:00:00",
    end: "2026-05-28T21:00:00",
    recurrence: {
      frequency: "Monthly",
      rule: "Last Thursday of each month",
    },
    speaker: "Church board chair",
    capacity: 32,
    registrationRequired: false,
    volunteersNeeded: 2,
    budgetAllocated: 80000,
    budgetSpent: 30000,
    status: "Approved",
    attendance: {
      registered: 28,
      actual: 24,
      members: 24,
      visitors: 0,
      followUpRequired: 0,
      conversions: 0,
      baptisms: 0,
    },
    volunteers: [
      {
        role: "Minutes secretary",
        assignee: "Church clerk",
        department: "Clerk",
        status: "Confirmed",
        callTime: "18:45",
      },
      {
        role: "Finance brief",
        assignee: "Treasurer",
        department: "Treasury",
        status: "Confirmed",
        callTime: "18:45",
      },
    ],
    communications: {
      channels: ["Email", "WhatsApp"],
      rsvpTracking: true,
      automations: ["Send agenda 48h before meeting"],
    },
    permissions: [
      {
        role: "Church clerk",
        scope: "Board documents",
        level: "View all",
      },
      {
        role: "Treasurer",
        scope: "Budget approvals",
        level: "Finance",
      },
    ],
    attachments: [
      {
        type: "Report",
        name: "May board agenda.pdf",
        owner: "Church clerk",
        status: "Ready",
      },
      {
        type: "Budget",
        name: "Events budget approvals.xlsx",
        owner: "Treasury",
        status: "Ready",
      },
    ],
    notes: ["Review event approval queue and Pathfinder camp budget."],
    reports: ["Pending approvals: Pathfinder readiness and health outreach."],
    enterpriseReadiness: [
      { label: "Approval workflow", status: "Ready" },
      { label: "Multi-branch synchronization", status: "Planned" },
    ],
  },
  {
    id: "EVT-006",
    title: "Quarterly Communion Sabbath",
    description:
      "Communion service, foot washing coordination, and deacon/deaconess roster.",
    department: "Pastoral",
    category: "Communion",
    colorKey: "communion",
    venue: "Main sanctuary",
    start: "2026-06-06T09:00:00",
    end: "2026-06-06T13:30:00",
    recurrence: {
      frequency: "Quarterly",
      rule: "First Sabbath of each quarter",
    },
    speaker: "Pr. Daniel Kato",
    capacity: 540,
    registrationRequired: false,
    volunteersNeeded: 30,
    budgetAllocated: 1750000,
    budgetSpent: 980000,
    status: "Needs volunteers",
    attendance: {
      registered: 0,
      actual: 462,
      members: 430,
      visitors: 32,
      followUpRequired: 11,
      conversions: 2,
      baptisms: 0,
    },
    volunteers: [
      {
        role: "Deacons",
        assignee: "Needed",
        department: "Pastoral",
        status: "Needed",
        callTime: "08:00",
      },
      {
        role: "Deaconesses",
        assignee: "Deaconess team B",
        department: "Pastoral",
        status: "Assigned",
        callTime: "08:00",
      },
      {
        role: "Communion preparation",
        assignee: "Grace A.",
        department: "Pastoral",
        status: "Confirmed",
        callTime: "07:30",
      },
    ],
    communications: {
      channels: ["Email", "SMS", "WhatsApp", "Push"],
      rsvpTracking: false,
      automations: [
        "Notify deacons and deaconesses",
        "Reminder 24h before event",
      ],
    },
    permissions: [
      {
        role: "Pastor",
        scope: "Sacraments and major services",
        level: "Approve",
      },
    ],
    attachments: [
      {
        type: "Report",
        name: "Communion preparation checklist",
        owner: "Head deacon",
        status: "Ready",
      },
    ],
    notes: ["Volunteer shortage: 8 deacons required."],
    reports: ["Projected attendance: 470 based on previous communion trend."],
    enterpriseReadiness: [
      { label: "AI attendance predictions", status: "Designed" },
      { label: "Volunteer check-ins", status: "Designed" },
    ],
  },
  {
    id: "EVT-007",
    title: "Baptism Class and Bible Study",
    description:
      "Baptism preparation, Bible study review, and discipleship pathway orientation.",
    department: "Evangelism",
    category: "Baptism Class",
    colorKey: "evangelism",
    venue: "Classroom 2",
    start: "2026-05-22T17:30:00",
    end: "2026-05-22T19:00:00",
    recurrence: {
      frequency: "Weekly",
      rule: "Every Friday before Sabbath",
    },
    speaker: "Bible Worker Josephine A.",
    capacity: 48,
    registrationRequired: true,
    volunteersNeeded: 5,
    budgetAllocated: 180000,
    budgetSpent: 90000,
    status: "Approved",
    attendance: {
      registered: 31,
      actual: 27,
      members: 18,
      visitors: 9,
      followUpRequired: 12,
      conversions: 5,
      baptisms: 6,
    },
    volunteers: [
      {
        role: "Bible worker",
        assignee: "Josephine A.",
        department: "Evangelism",
        status: "Confirmed",
        callTime: "17:00",
      },
      {
        role: "Mentors",
        assignee: "Discipleship team",
        department: "Evangelism",
        status: "Assigned",
        callTime: "17:15",
      },
    ],
    communications: {
      channels: ["SMS", "WhatsApp"],
      rsvpTracking: true,
      automations: ["Send lesson reminder 24h before class"],
    },
    permissions: [
      {
        role: "Department leader",
        scope: "Baptism classes",
        level: "Manage",
      },
      {
        role: "Pastor",
        scope: "Baptism approvals",
        level: "Approve",
      },
    ],
    attachments: [
      {
        type: "Sermon notes",
        name: "Fundamental beliefs lesson 8.pdf",
        owner: "Evangelism department",
        status: "Ready",
      },
    ],
    notes: ["Six candidates are ready for pastoral review."],
    reports: ["Conversion tracking: 5 active interests this week."],
    enterpriseReadiness: [
      { label: "Ministry engagement scoring", status: "Ready" },
    ],
  },
  {
    id: "EVT-008",
    title: "Community Health Seminar",
    description:
      "Health education, blood pressure screening, and community outreach registration.",
    department: "Health",
    category: "Health Seminar",
    colorKey: "health",
    venue: "Community hall",
    start: "2026-06-14T10:00:00",
    end: "2026-06-14T15:00:00",
    recurrence: {
      frequency: "Monthly",
      rule: "Second Sunday of each month",
    },
    speaker: "Dr. Lydia N.",
    capacity: 220,
    registrationRequired: true,
    volunteersNeeded: 18,
    budgetAllocated: 2200000,
    budgetSpent: 1180000,
    status: "Pending approval",
    attendance: {
      registered: 164,
      actual: 0,
      members: 0,
      visitors: 0,
      followUpRequired: 0,
      conversions: 0,
      baptisms: 0,
    },
    volunteers: [
      {
        role: "Medical lead",
        assignee: "Dr. Lydia N.",
        department: "Health",
        status: "Confirmed",
        callTime: "09:00",
      },
      {
        role: "Registration desk",
        assignee: "Community services team",
        department: "Community Services",
        status: "Assigned",
        callTime: "09:15",
      },
      {
        role: "Follow-up counselors",
        assignee: "Needed",
        department: "Evangelism",
        status: "Needed",
        callTime: "09:30",
      },
    ],
    communications: {
      channels: ["Email", "SMS", "WhatsApp", "Push"],
      rsvpTracking: true,
      automations: [
        "Reminder 24h before event",
        "Notify volunteers",
        "Follow-up after outreach",
      ],
    },
    permissions: [
      {
        role: "Department leader",
        scope: "Health outreach",
        level: "Manage",
      },
      {
        role: "Pastor",
        scope: "Public outreach",
        level: "Approve",
      },
      {
        role: "Treasurer",
        scope: "Outreach budget",
        level: "Finance",
      },
    ],
    attachments: [
      {
        type: "Poster",
        name: "Health seminar community poster.png",
        owner: "Health department",
        status: "Ready",
      },
      {
        type: "Budget",
        name: "Health seminar budget.xlsx",
        owner: "Treasury",
        status: "Draft",
      },
    ],
    notes: ["Pending approval because budget variance is above threshold."],
    reports: ["Projected visitor ratio: 67% based on registrations."],
    enterpriseReadiness: [
      { label: "QR check-in", status: "Designed" },
      { label: "Ticketing/registration", status: "Ready" },
    ],
  },
  {
    id: "EVT-009",
    title: "Evangelism Campaign Opening Night",
    description:
      "Public evangelism campaign with nightly sermons, decision cards, and follow-up teams.",
    department: "Evangelism",
    category: "Evangelism",
    colorKey: "evangelism",
    venue: "Outdoor tent",
    start: "2026-06-20T18:00:00",
    end: "2026-06-20T20:30:00",
    recurrence: {
      frequency: "None",
      rule: "Campaign opening night",
    },
    speaker: "Evangelist Peter O.",
    capacity: 900,
    registrationRequired: true,
    volunteersNeeded: 44,
    budgetAllocated: 9200000,
    budgetSpent: 6100000,
    status: "Approved",
    attendance: {
      registered: 540,
      actual: 0,
      members: 0,
      visitors: 0,
      followUpRequired: 0,
      conversions: 0,
      baptisms: 0,
    },
    volunteers: [
      {
        role: "Decision-card team",
        assignee: "Evangelism team A",
        department: "Evangelism",
        status: "Assigned",
        callTime: "17:00",
      },
      {
        role: "Ushers",
        assignee: "Deacon team C",
        department: "Pastoral",
        status: "Confirmed",
        callTime: "17:00",
      },
      {
        role: "Media and livestream",
        assignee: "Media rotation 1",
        department: "Music",
        status: "Assigned",
        callTime: "16:30",
      },
    ],
    communications: {
      channels: ["Email", "SMS", "WhatsApp", "Push"],
      rsvpTracking: true,
      automations: [
        "Reminder 24h before event",
        "Notify volunteers",
        "Follow-up after outreach",
      ],
    },
    permissions: [
      {
        role: "Department leader",
        scope: "Evangelism campaigns",
        level: "Manage",
      },
      {
        role: "Pastor",
        scope: "Major campaigns",
        level: "Approve",
      },
      {
        role: "Treasurer",
        scope: "Campaign budget",
        level: "Finance",
      },
    ],
    attachments: [
      {
        type: "Poster",
        name: "Campaign opening night poster.png",
        owner: "Evangelism department",
        status: "Ready",
      },
      {
        type: "Report",
        name: "Campaign readiness report.pdf",
        owner: "Campaign secretary",
        status: "Ready",
      },
    ],
    notes: ["Decision-card data should feed follow-up queue nightly."],
    reports: ["Volunteer coverage: 39 of 44 roles assigned."],
    enterpriseReadiness: [
      { label: "Livestream integration", status: "Designed" },
      { label: "AI attendance predictions", status: "Designed" },
      { label: "Multi-branch synchronization", status: "Planned" },
    ],
  },
  {
    id: "EVT-010",
    title: "Choir Practice for Sabbath Music",
    description:
      "Choir rehearsal, special item preparation, and worship music coordination.",
    department: "Music",
    category: "Choir Practice",
    colorKey: "choir",
    venue: "Choir room",
    start: "2026-05-21T18:30:00",
    end: "2026-05-21T20:00:00",
    recurrence: {
      frequency: "Weekly",
      rule: "Every Thursday evening",
    },
    speaker: "Choir Director Esther M.",
    capacity: 64,
    registrationRequired: false,
    volunteersNeeded: 4,
    budgetAllocated: 90000,
    budgetSpent: 60000,
    status: "Approved",
    attendance: {
      registered: 0,
      actual: 42,
      members: 42,
      visitors: 0,
      followUpRequired: 0,
      conversions: 0,
      baptisms: 0,
    },
    volunteers: [
      {
        role: "Choir director",
        assignee: "Esther M.",
        department: "Music",
        status: "Confirmed",
        callTime: "18:15",
      },
      {
        role: "Pianist",
        assignee: "Joel M.",
        department: "Music",
        status: "Confirmed",
        callTime: "18:15",
      },
    ],
    communications: {
      channels: ["WhatsApp"],
      rsvpTracking: false,
      automations: ["Send music list Thursday 08:00"],
    },
    permissions: [
      {
        role: "Department leader",
        scope: "Music rehearsals",
        level: "Manage",
      },
    ],
    attachments: [
      {
        type: "Sermon notes",
        name: "Sabbath special item lyrics.pdf",
        owner: "Music department",
        status: "Ready",
      },
    ],
    notes: ["Prepare communion hymn set for June 6."],
    reports: ["Choir attendance stable at 84% participation."],
    enterpriseReadiness: [{ label: "Media library", status: "Designed" }],
  },
];
